# Generated by Django 3.0.4 on 2020-03-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='surname',
            new_name='firstname',
        ),
    ]
