# Generated by Django 3.0.4 on 2020-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200328_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contracttime',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
