# Generated by Django 3.0.4 on 2020-03-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20200328_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentre',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Customer'),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bz',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='caretime',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='comments',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='customer',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Contract'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contracttime',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='handicap',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='handicap_number',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='heads',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date scraped'),
        ),
        migrations.AddField(
            model_name='customer',
            name='servicetype',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='timequota',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Customer'),
        ),
        migrations.AddField(
            model_name='department',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='comments',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
