# Generated by Django 3.0.4 on 2020-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20200328_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='senior',
            field=models.BooleanField(default=False),
        ),
    ]
