# Generated by Django 3.0.4 on 2020-03-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20200328_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contract',
        ),
    ]
