# Generated by Django 3.0.4 on 2020-03-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20200328_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='servicetype',
        ),
        migrations.AddField(
            model_name='customer',
            name='servicetypes',
            field=models.ManyToManyField(to='employees.ServiceType'),
        ),
    ]
