# Generated by Django 3.0.4 on 2020-04-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_department_servicetypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costcentres', to='employees.Department'),
        ),
    ]
